### ISSUE TITLE
Add "backplateTemperature" to Nest Thermostat Devices

### ISSUE THREAD

**Issue by ttravisswan** [ThomasLomas/ha-starlinghomehub#102]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ThomasLomas/ha-starlinghomehub/issues?q=is%3Aissue+label%3A%22enhancement%22).

### Is your feature request related to a problem? Please describe.

When a wireless temperature sensor is selected to use as the reference temperature to trigger heating/cooling, the temperature at the thermostat itself, as viewed in Home Assistant, is overwritten by the temperature of the wireless temp sensor. This makes tracking temperatures by room, over time, impossible in Home Assistant because the data source for the thermostat's "temperature" reading can change.

### Describe the solution you'd like

Referencing [Starling's API documentation](https://sidewinder.starlinghome.io/sdc/#thermostat), "Thermostat" devices have two temperature measurement values:

backplateTemperature: Temperature at the thermostat, in degrees C

currentTemperature: Temperature at the currently active Temperature Sensor, in degrees C. If no Temperature Sensors are present, or none is active, returns the temperature at the thermostat.

Right now, it appears "currentTemperature" is the only value available for thermostats in Home Assistant. Can you please add "backplateTemperature" to the device in Home Assistant to report the temperature at the thermostat, regardless of whether a temperature sensor is selected or not?

### Describe alternatives you've considered

Other than simply not using the temperature sensors for heating/cooling purposes, there is no alternative for this problem.

### Additional context

There is a "temperature" value in Home Assistant that appears to always report "null." I'm not sure whether that's just a placeholder or if this is related to the subject issue.

**Comment by ThomasLomas** [comment]
Does it make sense for `backplateTemperature` to be used as the temperature reported in the climate entity? Or just as a separate sensor value?

**Comment by ttravisswan** [comment]
I don't think so, since I believe "temperature" in the climate entity is used to determine whether heating or cooling needs to be called for (and when to stop), which should be the temperature of _either_ the thermostat itself or the value of the active temperature sensor, if one is selected. It would probably make more sense to add `backplateTemperature` as a separate sensor value.

**Comment by ThomasLomas** [comment]
No problem. This has been added. Thanks!
