### ISSUE TITLE
No devices discovered

### ISSUE THREAD

**Issue by ajwoodb** [ThomasLomas/ha-starlinghomehub#63]
## System Information

version | core-2024.8.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Asia/Dubai
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.0
Stage | running
Available Repositories | 1457
Downloaded Repositories | 18

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | March 29, 2025 at 4:00 AM
relayer_connected | true
relayer_region | ap-southeast-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 937.9 GB
disk_used | 174.1 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Silicon Labs Multiprotocol (2.4.5), Let's Encrypt (5.1.3), Matter Server (6.4.2), Home Assistant Google Drive Backup (0.112.1), Mosquitto broker (6.4.1), Node-RED (18.0.5), Duck DNS (1.18.0), File editor (5.8.0), InfluxDB (5.0.0), Grafana (10.0.0), Advanced SSH & Web Terminal (18.0.0), GoSungrow (3.0.7), JupyterLab (0.15.2), MariaDB (2.7.1), Hass.io Community Store (1.30.1), OpenThread Border Router (2.10.0), ModbusTCP2MQTT (0.3.9.1), PostgreSQL (1.0.0), TeslaMate (0.22.0), Dashboard Infographic Server (1.6.6), Remote API proxy (1.3.0), HomeBot AI Insightsv2 (0.5.9.6.2), Samba share (12.3.2), Dnsmasq (1.8.1), HomeBot API (0.9.2), HomeBot API Alpha (0.2.3.6), SQLite Web (4.2.0), HA Vision Insights (0.0.1.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 10
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 25, 2023 at 5:41 AM
-- | --
current_recorder_run | September 3, 2024 at 9:46 PM
estimated_db_size | 24892.16 MiB
database_engine | mysql
database_version | 10.11.6

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ThomasLomas/starling_home_hub/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I am able to add the integration via HACS and api key is working. The integration however does not find any devices. 

### Reproduction steps

1. starling hub v15
2.
3.
...

### Debug logs

```text
na
```

### Diagnostics dump

na

**Comment by Briadark** [comment]
I'm having the same issue.

**Comment by ajwoodb** [comment]
Nest Cam with Floodlight is GA02411-US.

**Comment by ThomasLomas** [comment]
Right now the camera support is work in progress and such I haven’t enabled it.

when I’m back In a week or so I will try enable all the devices and then fill in the functionality in between.

**Comment by ThomasLomas** [comment]
@ajwoodb The latest Starling update enables RTSP for the cameras. That would integrate with Home Assistant's generic camera. May be something to consider.

**Comment by ThomasLomas** [comment]
RTSP support has been added and Web RTC will follow. Please upgrade both your Starling Home Hub and this integration to utilize.
