### ISSUE TITLE
Thermostats would be so great to add someday

### ISSUE THREAD

**Issue by memarkham303** [ThomasLomas/ha-starlinghomehub#67]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ThomasLomas/starling_home_hub/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I'm relatively new to the Home Assistant world and found some complicated instructions on how to create a Google Cloud Project that allows for access to Google Nest products.  I'm using that to access my Nest Thermostats (4th Gen), however, the process was somewhat complicated and had many steps.

I then found this project and I also have a Starling Home Hob.  You've done such an amazing job tapping into the Starling API on the device to access Nest Protects. Thank you for that!

If you ever had the time to extend the project to include Nest Thermostats, I think it would be a better integration that going to the Google Cloud Project steps.

### Describe the solution you'd like

It would be fantastic to see Nest Thermostats within Home Assistant.  I'm sure other people would want access to other stuff, but for now, I'm mostly interested in Thermostats.

### Describe alternatives you've considered

Google Cloud Project setup works, but it's probably more complicated than most people are willing to do.

### Additional context

I just want to express my gratitude for your work on this up to now. It's fantastic and a huge addition to the HA community.

**Comment by ThomasLomas** [comment]
I will try to figure out the thermostats. I don't personally use Nest thermostat so may need some trial and error.

**Comment by memarkham303** [comment]
I’ll be glad to test anything you might come up with. I have the thermostats for several years, and just upgraded to the newest version.

**Comment by ThomasLomas** [comment]
Sounds good, thanks. I am working on getting a mock server setup that I can hopefully use for development. I'm going to be on vacation for a couple weeks starting later this week so sorry this won't be fast.

**Comment by ThomasLomas** [comment]
Starling upgraded their API in the latest version to a v2. I've been able to use this to build a minimal version of thermostat. This is on the v1.0.1-pre pre-release version. 

It needs some more work for fan control and presets.

<img width="677" alt="image" src="https://github.com/user-attachments/assets/8b8da318-cf61-4692-89b4-b4db82e06218">

**Comment by memarkham303** [comment]
Great.  I upgraded my Starling today and also the 1.0.1-pre version of the integration and I'll let you know how it goes.

Next on my wishlist: the Google Temperature Sensors.  I have a few extra of those, in case you'd like one.

**Comment by ThomasLomas** [comment]
No problem - looks like my ecobee sensor is exposed so I can work with that.

**Comment by ThomasLomas** [comment]
v1.0.2-pre has support if you want to check it out. My sensor only has temperature so i've added the other values per the API spec but not able to test.

**Comment by memarkham303** [comment]
Hey Thomas,  this all looks great.  **Thank you so much.**  The Nest thermostats look and work great, as does the Nest temperature sensor.

**Comment by ThomasLomas** [comment]
Thank you for your help!

Will close this out as I have now released v1.0.5. Will continue to build out the thermostat support in future releases.
