### ISSUE TITLE
Portuguese language translation needs fixing

### ISSUE THREAD

**Issue by ThomasLomas** [ThomasLomas/ha-starlinghomehub#91]
### System Health details

NA

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ThomasLomas/ha-starlinghomehub/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

The Portugues language translation needs fixing since the changes made in the last update

### Reproduction steps

NA

### What Nest devices are you using?

NA

### Debug logs

```text
NA
```

**Comment by ThomasLomas** [comment]
@ViPeR5000 Are you able to help with re-translating the Portuguese please?

**Comment by ViPeR5000** [comment]
Done

**Comment by ThomasLomas** [comment]
Thank you!! Merged #92
