### ISSUE TITLE
Multiple camera support?

### ISSUE THREAD

**Issue by seannymurrs** [ThomasLomas/ha-starlinghomehub#93]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ThomasLomas/ha-starlinghomehub/issues?q=is%3Aissue+label%3A%22enhancement%22).

### Is your feature request related to a problem? Please describe.

I'm not sure if this should be a feature request or a bug report. I have two Nest cameras (one Nest IQ Outdoor and one Nest Hello doorbell), but only the Nest IQ is showing up in Home Assistant. I'm getting the sensors and buttons for the Hello, but no actual video stream. I'm not sure if this is a bug, or an issue where only one camera stream is supported at a time. If I should be getting streams for both, then I'll fill out a bug report.

### Describe the solution you'd like

I'd like to be able to view both of my camera streams in Home Assistant.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by ThomasLomas** [comment]
For the Hello make sure that RTSP has been enabled in the starling app. I dont have web rtc support working yet so this is the only option right now.

**Comment by ThomasLomas** [comment]
Ignore what I said. I see the issue. I will push up a fix.

**Comment by ThomasLomas** [comment]
Please update and let me know if this doesn't fix it. I have a nest doorbell and this resolved the problem for me.

**Comment by kenmaca** [comment]
Thanks! This also resolved it for me too.
