### ISSUE TITLE
Descriptive entity_ids for their respective devices

### ISSUE THREAD

**Issue by kenmaca** [ThomasLomas/ha-starlinghomehub#96]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ThomasLomas/ha-starlinghomehub/issues?q=is%3Aissue+label%3A%22enhancement%22).

### Is your feature request related to a problem? Please describe.

It's hard to find the sensor for a particular device you're writing an automation for because the `entity_id`'s are currently named without any context of the parent device name. For example: 

For my Foyer doorbell (named Foyer):

* `binary_sensor.motion_detected_6`
* `binary_sensor.person_detected_6`
* [... other sensors]

### Describe the solution you'd like

It'd be great if the `entity_id`'s were prefixed with their device name. For example, based on the above:

* `binary_sensor.foyer_foyer_motion_detected`
* `binary_sensor.foyer_foyer_person_detected`

Somewhat related but different: it'd be great if the friendly name also followed this pattern.

### Describe alternatives you've considered

I could rename each individually, but this will likely break during updates and is pretty tedious going through many devices.

### Additional context

For whatever reason, it seems like the `camera.*` entities are following this pattern and not the sensors.

**Comment by ThomasLomas** [comment]
Good news and bad news:

Good news is that v1.1.0 will resolve this for new entities going forward, as well as fix the name of any existing entities that haven't already been overwritten.

There is no danger of you changing something manually as every entity is tracked by a unique identifier - actually without this Home Assistant doesn't even allow the dialog to change the entities.

Bad news is that this won't fix entity keys you already have (names should update). For that I think you'll have to delete entities and reload the integration, or delete the integration entirely.
