### ISSUE TITLE
Add Device Category "home_away_control"

### ISSUE THREAD

**Issue by MarlinFF** [ThomasLomas/ha-starlinghomehub#98]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ThomasLomas/ha-starlinghomehub/issues?q=is%3Aissue+label%3A%22enhancement%22).

### Is your feature request related to a problem? Please describe.

In the future, can the Device Category "home_away_control" be added so that could manage the Home/Away function. Thank you.

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

N/A

### Additional context

I wanted to request this feature as I did not see it listed on your README. Thank you so much for creating this integration.

**Comment by ThomasLomas** [comment]
This was added in v1.0.8. Please report any issues in a new issue. Thanks!

**Comment by MarlinFF** [comment]
Thank you for adding this. It's working! I do notice there is a bit of delay to reflect home occupied on/off in HA

**Comment by ThomasLomas** [comment]
I will look into the delay
